api_platform:
  defaults:
    pagination_enabled: true
    cache_headers:
      etag: true
      max_age: 3600
      shared_max_age: 3600
      vary: ['Content-Type', 'Authorization', 'Origin']

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  formats:
    jsonld: [ 'application/ld+json' ]
    json:   [ 'application/json' ]
